NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

_rest:
    resource: "@DinnerTimeRestBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest